// ================================================== //
//                                                    //
// !!! THIS CODE IS AUTO-GENERATED, DO NOT MODIFY !!! //
//                                                    //
// generated on gen_time=<2023-01-28T11:06:00.000>    //
// generated by user=<Lorenzo Panieri>                //
//                                                    //
// ================================================== //

/*
#define BUILD_MAJOR_ "0"							// max 255
#define BUILD_MINOR_ "0"							// max 255
#define BUILD_PATCH_ "2"							// max 255
#define BUILD_PRE_RELEASE_TAG_ ""					// a < b < rc < none
#define BUILD_PRE_RELEASE_PATCH_ ""				// max 63
#define BUILD_BUILD_NUMBER_ ""					// max 2^64 - 1
*/

#define BUILD_LOG_LEVEL_ 0
#define BUILD_VERSION_ "v0.1.0"
// #define BUILD_PRE_RELEASE_
#define BUILD_LOCAL_BUILD_
#define BUILD_BUILD_NUMBER_ "0"

